#! /bin/csh -f
set filename = $1
cp ${filename}.cif tmp.cif
sed -i 's/(.*.)//g' tmp.cif
#
echo "TITLE" > tmp.xtl
echo "CELL"  >> tmp.xtl
#
set a = `awk '{if($1=="_cell_length_a"){print $2}}' tmp.cif`
set b = `awk '{if($1=="_cell_length_b"){print $2}}' tmp.cif`
set c = `awk '{if($1=="_cell_length_c"){print $2}}' tmp.cif`
set alpha = `awk '{if($1=="_cell_angle_alpha"){print $2}}' tmp.cif`
set beta  = `awk '{if($1=="_cell_angle_beta"){print $2}}' tmp.cif`
set gamma = `awk '{if($1=="_cell_angle_gamma"){print $2}}' tmp.cif`
awk -v a=${a} -v b=${b} -v c=${c} -v alpha=${alpha} -v beta=${beta} -v gamma=${gamma} '{if($1=="_cell_angle_gamma"){printf "%9.6f %9.6f %9.6f %9.6f %9.6f %9.6f \n", a, b, c, alpha, beta, gamma}}' tmp.cif >> tmp.xtl
# cif (old version)
sed -n -e 's/_symmetry_Int_Tables_number/SYMMETRY NUMBER /p' tmp.cif >> tmp.xtl
sed -n -e 's/_symmetry_space_group_name_H-M/SYMMETRY LABEL /p' tmp.cif | sed -e "s/'//g" >> tmp.xtl
# cif (new version)
sed -n -e 's/_space_group_IT_number/SYMMETRY NUMBER /p' tmp.cif >> tmp.xtl
sed -n -e 's/_space_group_name_H-M_alt/SYMMETRY LABEL /p' tmp.cif | sed -e "s/'//g" >> tmp.xtl
echo "ATOMS" >> tmp.xtl
echo "NAME         X           Y           Z" >> tmp.xtl
#
# cif (old version)
awk '{if(($3 ~/^[0-9].[0-9]+$/) && ($4 ~/^[0-9].[0-9]+$/) && ($6 != "Biso")){printf "%-10s %10.6f %10.6f %10.6f \n",$1, $3, $4, $5}}' tmp.cif >> tmp.xtl
# cif (new version)
awk '{if(($3 ~/^[0-9].[0-9]+$/) && ($4 ~/^[0-9].[0-9]+$/) && ($6 == "Biso")){sub("\r","",$8); printf "%-10s %10.6f %10.6f %10.6f \n",$8, $3, $4, $5}}' tmp.cif >> tmp.xtl
# ^[0-9]+$, ^\d{n}$, ^\d{n,}$, ^\d{m,n}$
# ^(0[0-9)+)$, ^([1-9][0-9]+$), -(\-)>\d+(\.\d{1,5})?$
# ^[1-9]\d+$, ^\-[1-9]\d+$
# ^[A-Za-z0-9]+$, ^.{1-20}$,^[A-Za-z]+$, ^[A-Z]+$, ^[a-z]+$
#
echo "EOF" >> tmp.xtl
mv tmp.xtl ${filename}.xtl

