#! /bin/csh -f
set filename = $1
cp ${filename}.vasp tmp.vasp
echo " (Version 3 format configuration file)" > tmp.cfg
echo " M    " >> tmp.cfg
echo " " >> tmp.cfg
echo "          0         0         0 moves generated, tried, accepted" >> tmp.cfg
echo "          0                     configurations saved" >> tmp.cfg
echo " " >> tmp.cfg
#
set total_atoms_list = `awk 'NR==7{print $0}' tmp.vasp`
set count = 0
set total_atoms = 0
foreach i (${total_atoms_list})
  set total_atoms = `echo "${total_atoms} + $i" | bc`
  @ count += 1
end
#
echo "       ${total_atoms} molecules (of all types)" >> tmp.cfg
echo "          ${count} types of molecule"  >> tmp.cfg
echo "          1 is the largest number of atoms in a molecule"  >> tmp.cfg
echo "          0 Euler angles are provided"  >> tmp.cfg
echo " " >> tmp.cfg
echo "          F (Box is not truncated octahedral)" >> tmp.cfg
echo "            Defining vectors are:" >> tmp.cfg
awk -v n=0.5 'NR==3{printf "              %10.6f     0.000000   0.000000 \n",($1)*n }' tmp.vasp >> tmp.cfg
awk -v n=0.5 'NR==4{printf "               0.000000  %10.6f     0.000000 \n",($2)*n }' tmp.vasp >> tmp.cfg
awk -v n=0.5 'NR==5{printf "               0.000000   0.000000  %10.6f \n", ($3)*n }' tmp.vasp >> tmp.cfg
#
set count = 0
set total_atoms = 0
foreach i (${total_atoms_list})
  @ count += 1
  echo " " >> tmp.cfg
  echo "      $i molecules of type  ${count}" >> tmp.cfg
  echo "          1 atomic sites" >> tmp.cfg
  echo "              0.000000   0.000000   0.000000" >> tmp.cfg
end
#
echo " " >> tmp.cfg
awk -v n=2 '(NR>=9){printf "%12.6f %12.6f %12.6f \n",($1-0.5)*n,($2-0.5)*n,($3-0.5)*n}' tmp.vasp >> tmp.cfg
mv tmp.cfg ${filename}.cfg
rm -f -r tmp.vasp

